# buildspec.yml is the instruction file for CodeBuild.

version: 0.2

phases:
  pre_build:
    commands:
      # - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      # - echo Login successful.

  build:
    commands:
      # - echo Extracting branch name...
      - BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | sed 's/refs\/heads\///')  # Extracts name of branch
      # - echo Building the Docker image for branch $BRANCH_NAME...
      - docker build -t frontend-webapp:main .
      # - echo Tagging the Docker image...
      - docker tag frontend-webapp:$BRANCH_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$BRANCH_NAME

  post_build:
    commands:
      # - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$BRANCH_NAME
      
      - aws ssm get-parameter --name /codebuild/ssh --with-decryption --query "Parameter.Value" --output text > /tmp/ssh-key.pem
      - chmod 600 /tmp/ssh-key.pem

      # - echo "Connecting to EC2 and deploying the new image..."
      - |
        ssh -o StrictHostKeyChecking=no -i /tmp/ssh-key.pem ubuntu@100.53.177.18 << 'EOF'
        # echo "Connected to EC2"
        cd /home/ubuntu/app/devops-webapp
        docker compose up -d --force-recreate
        EOF
